---
title: "Participación ciudadana juvenil: entre la Reproducción social y la socialización política."
subtitle:  FONDECYT Iniciación 11190508 (2019-2022).
summary: "Este proyecto FONDECYT de Iniciación (2019 - 2022) trata acerca de la siguiente pregunta de investigación general: ¿Cuáles son los factores y mecanismos que explican la transmisión intergeneracional de la desigualdad política? Para responder esta pregunta global se analizará el rol que cumplen tanto las características socioeconómicas como las prácticas de socialización política de la familia para el desarrollo de diferentes tipos de participación ciudadana que manifiestan los jóvenes, tales como participación formal, participación activista y/o participación comunitaria. Adicionalmente, se evaluará la estabilidad o cambio de estas fuentes de socialización en diferentes momentos del desarrollo juvenil."
tags:
- Fondecyt Iniciación
date: "2021-03-31T00:00:00Z"

# Optional external URL for project (replaces project detail page).
external_link: ""

image:
#  caption: Photo by rawpixel on Unsplash
  focal_point: Smart

links:
#- icon: twitter
#  icon_pack: fab
#  name: Follow
#  url: https://twitter.com/georgecushen
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""

# Slides (optional).
#   Associate this project with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
#slides: example

authors: ["b-dmiranda"]
---

# Resumen


A pesar de la importancia de la persistente desigualdad política y los bajos niveles de involucramiento ciudadano juvenil no se sabe demasiado acerca de cómo los procesos de socialización reproducen y/o socializan estas desigualdades de una generación a otra. A este respecto, aunque es innegable la importancia de varios agentes de socialización política, como la escuela, existe un amplio consenso que plantea que el principal agente socializador de esta dimensión de la vida es la familia. Sin embargo, existen aún varios elementos necesarios de profundizar para comprender mejor el rol de la familia para el desarrollo de las formas de involucramiento ciudadano de los jóvenes. Primero, no es claro aún si esta transmisión se produce de igual manera con los diferentes tipos de participación. Segundo, si bien la transmisión de ventajas comparativas ha sido abordada ampliamente desde la sociología, expresado por ejemplo en el estudio de la transmisión del logro educacional o el estudio de la reproducción social, existe limitada evidencia acerca de cuáles son los mecanismos a través de los cuales opera esta transmisión en el ámbito político. Finalmente, no es claro si los efectos que tienen las condiciones socioeconómicas y/o las prácticas de socialización en edades tempranas se sostienen a lo largo del tiempo. 

Este proyecto trata acerca de la siguiente pregunta de investigación general: ¿Cuáles son los factores y mecanismos que explican la transmisión intergeneracional de la desigualdad política? Para responder esta pregunta global se analizará el rol que cumplen tanto las características socioeconómicas como las prácticas de socialización política de la familia para el desarrollo de diferentes tipos de participación ciudadana que manifiestan los jóvenes, tales como participación formal, participación activista y/o participación comunitaria. Adicionalmente, se evaluará la estabilidad o cambio de estas fuentes de socialización en diferentes momentos del desarrollo juvenil.

# Documentos

- [Formulación propuesta](formulacion-inic-daniel.pdf)

# Equipo

**Investigador principal** : Daniel Miranda (MIDE UC - Pontificia Universidad Católica de Chile).

**Asistentes de investigación:**
- Julio Iturra 
- Anais Herrera
- Pía Riff
- Jorge Matamala

**Periodo**: 2021-2022


# Repositorio

https://github.com/part-ciu-juv

# Tesistas
